### PR TITLE
Refactor Proxy Agent

### PR DESCRIPTION
**Pull request by adamisntdead**
# Why

The current way we were getting the root CA introduced a race condition against requests send early on from the SDK. To fix this, we have brought the proxy agent into the module so that we can wait for the CA to be obtained before sending off the required requests.

# How

- Remove `https-proxy-agent` as a dependency, instead bringing the code into the SDK and adding `agent-base` as a dependency.
- Wait for the promise getting the CA to be resolved before sending requests in the proxy agent

# Change Type

While behaviour is slightly changed, the API interface is the same and the behaviour is now as expected.

### CODE REVIEW

**Comment by adamisntdead** [comment]
Since I was bringing in code and consistency was badly needed in the repository anyway, I also ran prettier and added a pre-commit hook to have it run on commit. I will add a CI test for it at a later point

**Comment by adamisntdead** [comment]
I'd say reviewing the most recent commit is most worthwhile to get an idea of the changes that have been introduced, aside from style changes and code imports

**Review by davidnugent2425 — APPROVED** [review]
Tested locally 🔥

**Review by eoinboylan — APPROVED** [review]
LGTM

**Pull request merged**
