### PR TITLE
Deirdre/eng 1050 add new encrypted string format to node

### PR DESCRIPTION
**Pull request by DeirdreCleary**
# Why
We need to handle the new encrypted string format as discussed in the Duplicate Data doc

# How
Added new version prefix to the string to match the following format:
ev:[version]:[datatype]:Base64(KeyIV):Base64(ECDHPublicKey):Base64(AESEncryptedData):$

Also introduced tests to cover encrypted string format

### CODE REVIEW

**Comment by davidnugent2425** [comment]
This will be deployed if merged, do you know if it is ready to be deployed? Have our other systems started using the new version format yet?

**Review by eoinboylan — APPROVED** [review]
LGTM, just dont merge because it will auto deploy to NPM and e3 is not ready for new strings yet!

**Comment by adamisntdead** [comment]
This should be ready to merge now

**Pull request merged**
